wandb_version: 1

agent_name:
  desc: null
  value: BTR_og
game:
  desc: null
  value: BattleZone
steps:
  desc: null
  value: 5000
num_envs:
  desc: null
  value: 4
batch_size:
  desc: null
  value: 16
IQN:
  desc: null
  value: true
munchausen:
  desc: null
  value: true
impala:
  desc: null
  value: true
model_size:
  desc: null
  value: 4
noisy:
  desc: null
  value: true
per_alpha:
  desc: null
  value: 0.2
discount:
  desc: null
  value: 0.99
maxpool:
  desc: null
  value: true
stabiliser:
  desc: null
  value: target_net
target_replace:
  desc: null
  value: 8000
ema_tau:
  desc: null
  value: 0.001
tr_alpha:
  desc: null
  value: 1
tr_period:
  desc: null
  value: 1500
loss:
  desc: null
  value: huber
_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706553493.160724
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.11.0
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
