wandb_version: 1

agent_name:
  desc: null
  value: BTR_V100_32env_rr1_bs64_persplit4
game:
  desc: null
  value: NameThisGame
steps:
  desc: null
  value: 50000000
num_envs:
  desc: null
  value: 32
batch_size:
  desc: null
  value: 64
IQN:
  desc: null
  value: true
munchausen:
  desc: null
  value: true
impala:
  desc: null
  value: true
model_size:
  desc: null
  value: 2
noisy:
  desc: null
  value: false
per_alpha:
  desc: null
  value: 0.2
discount:
  desc: null
  value: 0.99
maxpool:
  desc: null
  value: true
stabiliser:
  desc: null
  value: target_net
target_replace:
  desc: null
  value: 8000
ema_tau:
  desc: null
  value: 0.001
tr_alpha:
  desc: null
  value: 1
tr_period:
  desc: null
  value: 1500
loss:
  desc: null
  value: huber
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706752580.57443
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 4
      - 16
      - 23
      - 42
      4: 3.11.7
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
